name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter_riverpod:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_maps_flutter: ^2.10.0
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  google_sign_in: ^6.2.2
  intl: ^0.18.0

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - .env
    - assets/fonts/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
  uses-material-design: true
